/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'single-challenges': SingleChallenge;
    'grouped-challenges': GroupedChallenge;
    notifications: Notification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'single-challenges': SingleChallengesSelect<false> | SingleChallengesSelect<true>;
    'grouped-challenges': GroupedChallengesSelect<false> | GroupedChallengesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Select the type of challenge, or choose "None"
   */
  challengeType: 'none' | 'single' | 'grouped';
  /**
   * Select a single challenge (required)
   */
  singleChallenge?: (string | null) | SingleChallenge;
  /**
   * Select a grouped challenge (required)
   */
  groupedChallenge?: (string | null) | GroupedChallenge;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "single-challenges".
 */
export interface SingleChallenge {
  id: string;
  /**
   * The publication status of the challenge
   */
  status: 'draft' | 'pending_approval' | 'published';
  /**
   * The name of the challenge
   */
  name: string;
  general: {
    /**
     * URL-friendly identifier
     */
    slug: string;
    /**
     * The date and time when the challenge will be launched
     */
    launchDate: string;
    /**
     * The grouped challenges that include this single challenge (automatically synced)
     */
    groupedChallenges?: (string | GroupedChallenge)[] | null;
  };
  /**
   * Add multiple distance groups for different measurement contexts
   */
  distances?:
    | {
        /**
         * The total distance of the challenge in kilometers as shown in the app
         */
        appDistanceKm: number;
        /**
         * The total distance of the challenge in miles as shown in the app
         */
        appDistanceMi: number;
        /**
         * The marketing distance in kilometers
         */
        marketingDistanceKm: number;
        /**
         * The marketing distance in miles
         */
        marketingDistanceMi: number;
        id?: string | null;
      }[]
    | null;
  routeDetails: {
    /**
     * The number of virtual postcards available in this challenge
     */
    virtualPostcards: number;
    /**
     * The number of local spots or checkpoints in this challenge
     */
    localSpots: number;
    /**
     * The type of map display to use for this challenge
     */
    mapType: 'roadmap' | 'satellite' | 'terrain' | 'hybrid';
    /**
     * The continent where this challenge takes place
     */
    continent: 'africa' | 'antarctica' | 'asia' | 'europe' | 'north_america' | 'oceania' | 'south_america';
  };
  media: {
    /**
     * Hex color code (e.g., #FF5733)
     */
    colorHex: string;
    /**
     * The image displayed on the front of the medal
     */
    medalFrontImage?: (string | null) | Media;
    /**
     * The image displayed on the back of the medal
     */
    medalBackImage?: (string | null) | Media;
    /**
     * The background image used for the challenge
     */
    backgroundImage?: (string | null) | Media;
    /**
     * The round sticker image for this challenge
     */
    roundStickerImage?: (string | null) | Media;
    /**
     * The video showcasing the medal
     */
    medalShowreelVideo?: (string | null) | Media;
    /**
     * The thumbnail image for the medal showreel video
     */
    medalShowreelThumbnail?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grouped-challenges".
 */
export interface GroupedChallenge {
  id: string;
  /**
   * The publication status of the challenge
   */
  status: 'draft' | 'pending_approval' | 'published';
  /**
   * The name of the challenge
   */
  name: string;
  general: {
    /**
     * URL-friendly identifier
     */
    slug: string;
    /**
     * The date and time when the challenge will be launched
     */
    launchDate: string;
    /**
     * Select the individual challenges that are part of this group
     */
    challenges: (string | SingleChallenge)[];
  };
  /**
   * Add multiple distance groups for different measurement contexts
   */
  distances?:
    | {
        /**
         * The total distance of the challenge in kilometers as shown in the app
         */
        appDistanceKm: number;
        /**
         * The total distance of the challenge in miles as shown in the app
         */
        appDistanceMi: number;
        /**
         * The marketing distance in kilometers
         */
        marketingDistanceKm: number;
        /**
         * The marketing distance in miles
         */
        marketingDistanceMi: number;
        id?: string | null;
      }[]
    | null;
  routeDetails: {
    /**
     * The number of virtual postcards available in this challenge
     */
    virtualPostcards: number;
    /**
     * The number of local spots or checkpoints in this challenge
     */
    localSpots: number;
    /**
     * The type of map display to use for this challenge
     */
    mapType: 'roadmap' | 'satellite' | 'terrain' | 'hybrid';
    /**
     * The continent where this challenge takes place
     */
    continent: 'africa' | 'antarctica' | 'asia' | 'europe' | 'north_america' | 'oceania' | 'south_america';
  };
  media: {
    /**
     * Hex color code (e.g., #FF5733)
     */
    colorHex: string;
    /**
     * The image displayed on the front of the medal
     */
    medalFrontImage?: (string | null) | Media;
    /**
     * The image displayed on the back of the medal
     */
    medalBackImage?: (string | null) | Media;
    /**
     * The background image used for the challenge
     */
    backgroundImage?: (string | null) | Media;
    /**
     * The header image displayed at the top of the grouped challenge
     */
    headerImage?: (string | null) | Media;
    /**
     * The round sticker image for this challenge
     */
    roundStickerImage?: (string | null) | Media;
    /**
     * The video showcasing the medal
     */
    medalShowreelVideo?: (string | null) | Media;
    /**
     * The thumbnail image for the medal showreel video
     */
    medalShowreelThumbnail?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  message: string;
  challenge?:
    | ({
        relationTo: 'single-challenges';
        value: string | SingleChallenge;
      } | null)
    | ({
        relationTo: 'grouped-challenges';
        value: string | GroupedChallenge;
      } | null);
  editor?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'single-challenges';
        value: string | SingleChallenge;
      } | null)
    | ({
        relationTo: 'grouped-challenges';
        value: string | GroupedChallenge;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  challengeType?: T;
  singleChallenge?: T;
  groupedChallenge?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "single-challenges_select".
 */
export interface SingleChallengesSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  general?:
    | T
    | {
        slug?: T;
        launchDate?: T;
        groupedChallenges?: T;
      };
  distances?:
    | T
    | {
        appDistanceKm?: T;
        appDistanceMi?: T;
        marketingDistanceKm?: T;
        marketingDistanceMi?: T;
        id?: T;
      };
  routeDetails?:
    | T
    | {
        virtualPostcards?: T;
        localSpots?: T;
        mapType?: T;
        continent?: T;
      };
  media?:
    | T
    | {
        colorHex?: T;
        medalFrontImage?: T;
        medalBackImage?: T;
        backgroundImage?: T;
        roundStickerImage?: T;
        medalShowreelVideo?: T;
        medalShowreelThumbnail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grouped-challenges_select".
 */
export interface GroupedChallengesSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  general?:
    | T
    | {
        slug?: T;
        launchDate?: T;
        challenges?: T;
      };
  distances?:
    | T
    | {
        appDistanceKm?: T;
        appDistanceMi?: T;
        marketingDistanceKm?: T;
        marketingDistanceMi?: T;
        id?: T;
      };
  routeDetails?:
    | T
    | {
        virtualPostcards?: T;
        localSpots?: T;
        mapType?: T;
        continent?: T;
      };
  media?:
    | T
    | {
        colorHex?: T;
        medalFrontImage?: T;
        medalBackImage?: T;
        backgroundImage?: T;
        headerImage?: T;
        roundStickerImage?: T;
        medalShowreelVideo?: T;
        medalShowreelThumbnail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  message?: T;
  challenge?: T;
  editor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}